# Generated by Django 3.2.18 on 2023-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=150)),
                ('cliente', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField()),
                ('preventa', models.CharField(max_length=50)),
                ('dias_venta', models.IntegerField()),
                ('prob_cierre', models.FloatField()),
                ('ciudad_entrega', models.CharField(max_length=50)),
                ('account_manager', models.CharField(max_length=50)),
                ('enlace_mat_cost', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
