# Generated by Django 3.2.18 on 2023-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20230409_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancapacidad',
            name='productos',
            field=models.ManyToManyField(to='proyecto.Productos'),
        ),
        migrations.AddField(
            model_name='plancapacidad',
            name='servicios',
            field=models.ManyToManyField(to='proyecto.Servicios'),
        ),
    ]
