# Generated by Django 3.2.18 on 2023-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20230409_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
