# Generated by Django 3.2.18 on 2023-04-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20230409_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='plancapacidad',
            name='account_manager',
        ),
        migrations.AddField(
            model_name='plancapacidad',
            name='Comercial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto.comercial'),
        ),
    ]
