# Generated by Django 3.2.18 on 2023-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20230409_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancapacidad',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='proyecto.Servicio'),
        ),
    ]
