# Generated by Django 3.2.18 on 2023-04-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_alter_plancapacidad_servicios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanCapacidadServicio',
        ),
    ]
